using IDManager.Domain.Enums;

namespace IDManager.Domain.Entities;

public class UserEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Phone { get; set; } = string.Empty;
    public string PasswordHash { get; set; } = string.Empty;
    public UserRole Role { get; set; } = UserRole.User;
    public bool IsActive { get; set; } = true;
    public int Points { get; set; }

    /// The member who created this account - their "parent" in the member network
    /// (docs/member-hierarchy.md), who a card generated by this member credits points to.
    public int? CreatedById { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime ModifiedAt { get; set; } = DateTime.UtcNow;
}
