using IDManager.Domain.Enums;

namespace IDManager.Domain.Entities;

public class UserEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Phone { get; set; } = string.Empty;
    public string PasswordHash { get; set; } = string.Empty;
    public UserRole Role { get; set; } = UserRole.User;
    public bool IsActive { get; set; } = true;
    public int Points { get; set; }

    /// The user who created this account (Admin creates Distributors, Distributor
    /// creates Users) - the "parent" that a card generated by this user credits
    /// points back to.
    public int? CreatedById { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime ModifiedAt { get; set; } = DateTime.UtcNow;
}
