using IDManager.Domain.Enums;

namespace IDManager.Domain.Entities;

public class UserEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Phone { get; set; } = string.Empty;
    public string PasswordHash { get; set; } = string.Empty;
    public UserRole Role { get; set; } = UserRole.User;
    public bool IsActive { get; set; } = true;
    public int Points { get; set; }

    /// The member who created this account - their "parent" in the member network
    /// (docs/member-hierarchy.md), who a card generated by this member credits points to.
    public int? CreatedById { get; set; }

    // Optional profile details - none of them is required.

    /// The member's shop.
    public string? ShopName { get; set; }
    public string? ShopAddress { get; set; }
    public string? City { get; set; }
    public string? Pincode { get; set; }

    /// Their identity proof: what kind of ID it is (Aadhaar, Voter ID ...) and its number. The
    /// front and back images live in UserIdentityEntity so they are only loaded when asked for.
    public string? IdType { get; set; }
    public string? IdNumber { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime ModifiedAt { get; set; } = DateTime.UtcNow;
}
